=== BackupTheBerlios/ccl-plugin/CCLPlugin/build_classes/org/cocons/uml/ccl/ccl10.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XML Spy v3.5 NT (http://www.xmlspy.com) by  () -->
<!--DTD generated by XML Spy v3.5 NT (http://www.xmlspy.com)-->
<!ELEMENT Foundation.Core.Attribute (Foundation.Core.ModelElement.name, Foundation.Core.ModelElement.isSpecification, Foundation.Core.Feature.owner, Foundation.Core.StructuralFeature.type, Foundation.Core.ModelElement.referenceTag?)>
<!ATTLIST Foundation.Core.Attribute
	xmi.id (xmi.14 | xmi.17 | xmi.18) #REQUIRED
>
<!ELEMENT Foundation.Core.Class (Foundation.Core.ModelElement.name, Foundation.Core.ModelElement.isSpecification, Foundation.Core.GeneralizableElement.isRoot, Foundation.Core.GeneralizableElement.isLeaf, Foundation.Core.GeneralizableElement.isAbstract, Foundation.Core.Class.isActive, Foundation.Core.ModelElement.namespace, Foundation.Core.ModelElement.taggedValue, Foundation.Core.Classifier.feature)>
<!ATTLIST Foundation.Core.Class
	xmi.id CDATA #REQUIRED
>
<!ELEMENT Foundation.Core.Class.isActive EMPTY>
<!ATTLIST Foundation.Core.Class.isActive
	xmi.value CDATA #REQUIRED
>
<!ELEMENT Foundation.Core.Classifier (Foundation.Core.ModelElement.name?, Foundation.Core.ModelElement.isSpecification?, Foundation.Core.GeneralizableElement.isRoot?, Foundation.Core.GeneralizableElement.isLeaf?, Foundation.Core.GeneralizableElement.isAbstract?, Foundation.Core.ModelElement.namespace?)>
<!ATTLIST Foundation.Core.Classifier
	xmi.id CDATA #IMPLIED
	xmi.idref (xmi.13 | xmi.3) #IMPLIED
>
<!ELEMENT Foundation.Core.Classifier.feature (Foundation.Core.Attribute+)>
<!ELEMENT Foundation.Core.Constraint (Foundation.Core.ModelElement.name, Foundation.Core.ModelElement.isSpecification, Foundation.Core.Constraint.constrainedStereotype)>
<!ATTLIST Foundation.Core.Constraint
	xmi.id CDATA #REQUIRED
>
<!ELEMENT Foundation.Core.Constraint.constrainedStereotype (Foundation.Extension_Mechanisms.Stereotype)>
<!ELEMENT Foundation.Core.Feature.owner (Foundation.Core.Classifier)>
<!ELEMENT Foundation.Core.GeneralizableElement.isAbstract EMPTY>
<!ATTLIST Foundation.Core.GeneralizableElement.isAbstract
	xmi.value CDATA #REQUIRED
>
<!ELEMENT Foundation.Core.GeneralizableElement.isLeaf EMPTY>
<!ATTLIST Foundation.Core.GeneralizableElement.isLeaf
	xmi.value CDATA #REQUIRED
>
<!ELEMENT Foundation.Core.GeneralizableElement.isRoot EMPTY>
<!ATTLIST Foundation.Core.GeneralizableElement.isRoot
	xmi.value CDATA #REQUIRED
>
<!ELEMENT Foundation.Core.ModelElement EMPTY>
<!ATTLIST Foundation.Core.ModelElement
	xmi.idref (xmi.14 | xmi.3) #REQUIRED
>
<!ELEMENT Foundation.Core.ModelElement.isSpecification EMPTY>
<!ATTLIST Foundation.Core.ModelElement.isSpecification
	xmi.value CDATA #REQUIRED
>
<!ELEMENT Foundation.Core.ModelElement.name (#PCDATA)>
<!ELEMENT Foundation.Core.ModelElement.namespace (Foundation.Core.Namespace)>
<!ELEMENT Foundation.Core.ModelElement.referenceTag (Foundation.Extension_Mechanisms.TaggedValue)>
<!ELEMENT Foundation.Core.ModelElement.taggedValue (Foundation.Extension_Mechanisms.TaggedValue+)>
<!ELEMENT Foundation.Core.Namespace EMPTY>
<!ATTLIST Foundation.Core.Namespace
	xmi.idref CDATA #REQUIRED
>
<!ELEMENT Foundation.Core.Namespace.ownedElement (Foundation.Extension_Mechanisms.Stereotype, Foundation.Core.Classifier, Foundation.Core.Class, Foundation.Extension_Mechanisms.TagDefinition)>
<!ELEMENT Foundation.Core.StructuralFeature.type (Foundation.Core.Classifier)>
<!ELEMENT Foundation.Data_Types.Multiplicity (Foundation.Data_Types.Multiplicity.range?)>
<!ATTLIST Foundation.Data_Types.Multiplicity
	xmi.id (xmi.10 | xmi.6) #IMPLIED
	xmi.idref CDATA #IMPLIED
>
<!ELEMENT Foundation.Data_Types.Multiplicity.range (Foundation.Data_Types.MultiplicityRange)>
<!ELEMENT Foundation.Data_Types.MultiplicityRange (Foundation.Data_Types.MultiplicityRange.lower, Foundation.Data_Types.MultiplicityRange.upper)>
<!ATTLIST Foundation.Data_Types.MultiplicityRange
	xmi.id (xmi.11 | xmi.7) #REQUIRED
>
<!ELEMENT Foundation.Data_Types.MultiplicityRange.lower (#PCDATA)>
<!ELEMENT Foundation.Data_Types.MultiplicityRange.upper (#PCDATA)>
<!ELEMENT Foundation.Extension_Mechanisms.Stereotype (Foundation.Core.ModelElement.name?, Foundation.Core.ModelElement.isSpecification?, Foundation.Core.GeneralizableElement.isRoot?, Foundation.Core.GeneralizableElement.isLeaf?, Foundation.Core.GeneralizableElement.isAbstract?, Foundation.Extension_Mechanisms.Stereotype.baseClass?, Foundation.Core.ModelElement.namespace?, Foundation.Extension_Mechanisms.Stereotype.extendedElement?, Foundation.Extension_Mechanisms.Stereotype.stereotypeConstraint?, Foundation.Extension_Mechanisms.Stereotype.definedTag?)>
<!ATTLIST Foundation.Extension_Mechanisms.Stereotype
	xmi.id CDATA #IMPLIED
	xmi.idref CDATA #IMPLIED
>
<!ELEMENT Foundation.Extension_Mechanisms.Stereotype.baseClass (#PCDATA)>
<!ELEMENT Foundation.Extension_Mechanisms.Stereotype.definedTag (Foundation.Extension_Mechanisms.TagDefinition+)>
<!ELEMENT Foundation.Extension_Mechanisms.Stereotype.extendedElement (Foundation.Core.ModelElement)>
<!ELEMENT Foundation.Extension_Mechanisms.Stereotype.stereotypeConstraint (Foundation.Core.Constraint)>
<!ELEMENT Foundation.Extension_Mechanisms.TagDefinition (Foundation.Core.ModelElement.name?, Foundation.Core.ModelElement.isSpecification?, Foundation.Extension_Mechanisms.TagDefinition.tagType?, Foundation.Extension_Mechanisms.TagDefinition.multiplicity?, Foundation.Core.ModelElement.namespace?, Foundation.Extension_Mechanisms.TagDefinition.typedValue?)>
<!ATTLIST Foundation.Extension_Mechanisms.TagDefinition
	xmi.id (xmi.16 | xmi.5 | xmi.9) #IMPLIED
	xmi.idref (xmi.16 | xmi.5 | xmi.9) #IMPLIED
>
<!ELEMENT Foundation.Extension_Mechanisms.TagDefinition.multiplicity (Foundation.Data_Types.Multiplicity)>
<!ELEMENT Foundation.Extension_Mechanisms.TagDefinition.tagType (#PCDATA)>
<!ELEMENT Foundation.Extension_Mechanisms.TagDefinition.typedValue (Foundation.Extension_Mechanisms.TaggedValue)>
<!ELEMENT Foundation.Extension_Mechanisms.TaggedValue (Foundation.Core.ModelElement.name?, Foundation.Core.ModelElement.isSpecification?, Foundation.Extension_Mechanisms.TaggedValue.dataValue?, Foundation.Extension_Mechanisms.TaggedValue.modelElement?, Foundation.Extension_Mechanisms.TaggedValue.referenceValue?, Foundation.Extension_Mechanisms.TaggedValue.type?)>
<!ATTLIST Foundation.Extension_Mechanisms.TaggedValue
	xmi.idref (xmi.12 | xmi.15 | xmi.8) #IMPLIED
	xmi.id (xmi.12 | xmi.15 | xmi.8) #IMPLIED
>
<!ELEMENT Foundation.Extension_Mechanisms.TaggedValue.dataValue (#PCDATA)>
<!ELEMENT Foundation.Extension_Mechanisms.TaggedValue.modelElement (Foundation.Core.ModelElement)>
<!ELEMENT Foundation.Extension_Mechanisms.TaggedValue.referenceValue (Foundation.Core.ModelElement)>
<!ELEMENT Foundation.Extension_Mechanisms.TaggedValue.type (Foundation.Extension_Mechanisms.TagDefinition)>
<!ELEMENT Model_Management.Model (Foundation.Core.ModelElement.isSpecification, Foundation.Core.GeneralizableElement.isRoot, Foundation.Core.GeneralizableElement.isLeaf, Foundation.Core.GeneralizableElement.isAbstract, Foundation.Core.Namespace.ownedElement)>
<!ATTLIST Model_Management.Model
	xmi.id CDATA #REQUIRED
>
<!ELEMENT XMI (XMI.header, XMI.content)>
<!ATTLIST XMI
	xmi.version CDATA #REQUIRED
>
<!ELEMENT XMI.content (Model_Management.Model)>
<!ELEMENT XMI.documentation (XMI.exporter, XMI.exporterVersion)>
<!ELEMENT XMI.exporter (#PCDATA)>
<!ELEMENT XMI.exporterVersion (#PCDATA)>
<!ELEMENT XMI.header (XMI.documentation, XMI.metamodel)>
<!ELEMENT XMI.metamodel EMPTY>
<!ATTLIST XMI.metamodel
	xmi.name CDATA #REQUIRED
	xmi.version CDATA #REQUIRED
>

=== BackupTheBerlios/ccl-plugin/ccl-plugin/CCL_Metamodel/XMLTest.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE XMI SYSTEM "org/cocons/uml/ccl/ccl10.dtd">
<XMI xmi.version="1.0">
  <XMI.header>
    <XMI.documentation>
      <XMI.exporter>Novosoft UML Library</XMI.exporter>
      <XMI.exporterVersion>0.4.19</XMI.exporterVersion>
    </XMI.documentation>
    <XMI.metamodel xmi.name="UML" xmi.version="1.3"/>
  </XMI.header>
  <XMI.content>
    <Model_Management.Model xmi.id="xmi.1">
      <Foundation.Core.ModelElement.isSpecification xmi.value="false"/>
      <Foundation.Core.GeneralizableElement.isRoot xmi.value="false"/>
      <Foundation.Core.GeneralizableElement.isLeaf xmi.value="false"/>
      <Foundation.Core.GeneralizableElement.isAbstract xmi.value="false"/>
      <Foundation.Core.Namespace.ownedElement>
        <Foundation.Extension_Mechanisms.TaggedValue xmi.id="xmi.2">
          <Foundation.Extension_Mechanisms.TaggedValue.dataValue>FirstValue</Foundation.Extension_Mechanisms.TaggedValue.dataValue>
          <Foundation.Extension_Mechanisms.TaggedValue.dataValue>SecondValue</Foundation.Extension_Mechanisms.TaggedValue.dataValue>
        </Foundation.Extension_Mechanisms.TaggedValue>
        <Foundation.Core.Class xmi.id="xmi.3">
          <Foundation.Core.ModelElement.name>myModelElement</Foundation.Core.ModelElement.name>
          <Foundation.Core.ModelElement.isSpecification xmi.value="false"/>
          <Foundation.Core.GeneralizableElement.isRoot xmi.value="false"/>
          <Foundation.Core.GeneralizableElement.isLeaf xmi.value="false"/>
          <Foundation.Core.GeneralizableElement.isAbstract xmi.value="false"/>
          <Foundation.Core.Class.isActive xmi.value="false"/>
          <Foundation.Core.ModelElement.namespace>
            <Foundation.Core.Namespace xmi.idref="xmi.1"/>
          </Foundation.Core.ModelElement.namespace>
        </Foundation.Core.Class>
      </Foundation.Core.Namespace.ownedElement>
    </Model_Management.Model>
  </XMI.content>
</XMI>
